apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: {{ .Values.api.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: read-configmaps
      containers:
      ## TODO Uncomment the following lines to enable the sidecar - was having issues with registry1
        # - name: sidecar
        #  image: registry1.dso.mil/ironbank/kiwigrid/k8s-sidecar:1.23.3
        #  volumeMounts:
        #  - name:  api-model
        #    mountPath: /config/
        #  env:
        #  - name: LABEL
        #    value: "leapfrogai"
        #  - name: FOLDER
        #    value: /config/
        #  - name: RESOURCE
        #    value: both
        #  - name: UNIQUE_FILENAMES
        #    value: "true"
        #  - name: NAMESPACE
        #    value: leapfrogai
        - name: api-container
          image: ghcr.io/defenseunicorns/leapfrog_api_server:0.1.0
          imagePullPolicy: Always
          env:
          - name: CONFIG_PATH
            value: /config/
          - name: GIN_MODE
            value: release
          - name: PORT
            value: "{{ .Values.api.port }}"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          - name: api-model
            mountPath: /config
      volumes:
      - name: api-model
        emptyDir: {}
        